/*******************************************************************
	FILE:		MFDataScanner.h
	
	COPYRIGHT:
		Copyright 2007-2008, the MacFire.org team.
		Use of this software is governed by the license terms
		indicated in the License.txt file (a BSD license).
	
	DESCRIPTION:
		A class to scan specific kinds of data.  It uses some rules
		similar to Xfire encoding rules.  It scans data generated by
		an MFDataEmitter.
	
	HISTORY:
		2008 04 06  Changed copyright to BSD license.
		2007 12 02  Added copyright notice.
		2007 12 01  Created.
*******************************************************************/

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

@interface MFDataScanner : NSObject
{
	NSData *_data;
	const unsigned char *_start;
	const unsigned char *_cur;
	const unsigned char *_end;
}

+ (id)scannerWithData:(NSData *)data;
- (id)initWithData:(NSData *)data;

- (UInt8)scanUInt8;
- (UInt16)scanUInt16;
- (UInt32)scanUInt32;
- (NSString *)scanString;
- (NSData *)scanData;

@end

